fix missing null terminator in tools/mkfs.c
strncpy does not write a null terminator if the src string is longer
than the dst size. If a user passed a filename that was longer than
DIRSIZ-1, then we would silently write a non-null-terminated string to
de.d_name. Instead, truncate at DIRSIZ-1, write a null terminator, and
emit a warning.

This bug triggered a warning on GCC 14.2.1:

tools/mkfs.c: In function ‘main’:
tools/mkfs.c:254:17: error: ‘__builtin_strncpy’ specified bound 254 equals destination size [-Werror=stringop-truncation]
  254 |                 strncpy(de.d_name, name, DIRSIZ);
      |                 ^